### ISSUE TITLE
Критическая ошибка при оформлении заказа

### ISSUE THREAD

**Issue by denism300** [cdek-it/wordpress#48]
При попытке оформить заказ критическая ошибка. В т.ч. на дефолтной теме "Twenty Twenty-Four".
Версии WP, WC и плагина последние на момент создания данного тикета.
![2024-10-15_20-31-20](https://github.com/user-attachments/assets/3851b555-7276-41ff-9bd9-ef5869e95db5)

**Comment by DEMAxx** [comment]
Добрый день! Подскажите какие данные отправляете в метод?

**Comment by denism300** [comment]
Добрый день!
Первый скриншот - пользователь ранее зарегистрирован, данные автоподставляются
![image](https://github.com/user-attachments/assets/8208e247-c81e-4bbf-8fef-ec847b21e9cb)
Второй скриншот - браузер в режиме инкогнито, пользователь не зарегистрирован. После ввода данных бесконечный прелоадер  на обновлении методов доставки, после обновления страницы такая же ошибка
![image](https://github.com/user-attachments/assets/f39e4296-3847-4f79-8970-5cedb6dfdd90)
Лог
`[16-Oct-2024 06:32:55 UTC] PHP Warning:  Undefined array key 0 in /var/www/u2624099/data/www/aaa.store/wp-content/plugins/cdekdelivery/src/CdekApi.php on line 296
[16-Oct-2024 06:32:55 UTC] PHP Warning:  Trying to access array offset on null in /var/www/u2624099/data/www/aaa.store/wp-content/plugins/cdekdelivery/src/CdekApi.php on line 296
[16-Oct-2024 06:32:55 UTC] PHP Fatal error:  Uncaught TypeError: Cdek\CdekApi::getCityCode(): Return value must be of type int, null returned in /var/www/u2624099/data/www/aaa.store/wp-content/plugins/cdekdelivery/src/CdekApi.php:296
Stack trace:
#0 /var/www/u2624099/data/www/aaa.store/wp-content/plugins/cdekdelivery/src/UI/CheckoutMap.php(32): Cdek\CdekApi->getCityCode('\xD0\x9C\xD0\xBE\xD1\x81\xD0\xBA\xD0\xB2\xD0\xB0', '123456')
#1 /var/www/u2624099/data/www/aaa.store/wp-includes/class-wp-hook.php(324): Cdek\UI\CheckoutMap->__invoke(Object(WC_Shipping_Rate), 0)
#2 /var/www/u2624099/data/www/aaa.store/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#3 /var/www/u2624099/data/www/aaa.store/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /var/www/u2624099/data/www/aaa.store/wp-content/themes/aaa/woocommerce/cart/cart-shipping.php(38): do_action('woocommerce_aft...', Object(WC_Shipping_Rate), 0)
#5 /var/www/u2624099/data/www/aaa.store/wp-content/plugins/woocommerce/includes/wc-core-functions.php(345): include('/var/www/u26240...')
#6 /var/www/u2624099/data/www/aaa.store/wp-content/plugins/woocommerce/includes/wc-cart-functions.php(247): wc_get_template('cart/cart-shipp...', Array)
#7 /var/www/u2624099/data/www/aaa.store/wp-content/themes/aaa/woocommerce/checkout/form-checkout.php(68): wc_cart_totals_shipping_html()
#8 /var/www/u2624099/data/www/aaa.store/wp-content/plugins/woocommerce/includes/wc-core-functions.php(345): include('/var/www/u26240...')
#9 /var/www/u2624099/data/www/aaa.store/wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-checkout.php(372): wc_get_template('checkout/form-c...', Array)
#10 /var/www/u2624099/data/www/aaa.store/wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-checkout.php(69): WC_Shortcode_Checkout::checkout()
#11 /var/www/u2624099/data/www/aaa.store/wp-content/plugins/woocommerce/includes/class-wc-shortcodes.php(72): WC_Shortcode_Checkout::output(Array)
#12 /var/www/u2624099/data/www/aaa.store/wp-content/plugins/woocommerce/includes/class-wc-shortcodes.php(95): WC_Shortcodes::shortcode_wrapper(Array, Array)
#13 /var/www/u2624099/data/www/aaa.store/wp-includes/shortcodes.php(434): WC_Shortcodes::checkout(Array, '', 'woocommerce_che...')
#14 [internal function]: do_shortcode_tag(Array)
#15 /var/www/u2624099/data/www/aaa.store/wp-includes/shortcodes.php(273): preg_replace_callback('/\\[(\\[?)(woocom...', 'do_shortcode_ta...', '[woocommerce_ch...')
#16 /var/www/u2624099/data/www/aaa.store/wp-includes/class-wp-hook.php(324): do_shortcode('[woocommerce_ch...')
#17 /var/www/u2624099/data/www/aaa.store/wp-includes/plugin.php(205): WP_Hook->apply_filters('[woocommerce_ch...', Array)
#18 /var/www/u2624099/data/www/aaa.store/wp-content/themes/aaa/inc/template-functions.php(196): apply_filters('the_content', '<!-- wp:tadv/cl...')
#19 /var/www/u2624099/data/www/aaa.store/wp-includes/class-wp-hook.php(326): template_html_excerpt('<!-- wp:tadv/cl...')
#20 /var/www/u2624099/data/www/aaa.store/wp-includes/plugin.php(205): WP_Hook->apply_filters('', Array)
#21 /var/www/u2624099/data/www/aaa.store/wp-includes/post-template.php(436): apply_filters('get_the_excerpt', '', Object(WP_Post))
#22 /var/www/u2624099/data/www/aaa.store/wp-content/plugins/wordpress-seo/src/helpers/post-helper.php(86): get_the_excerpt(Object(WP_Post))
#23 /var/www/u2624099/data/www/aaa.store/wp-content/plugins/wordpress-seo/src/presentations/indexable-post-type-presentation.php(196): Yoast\WP\SEO\Helpers\Post_Helper->get_the_excerpt(9)
#24 /var/www/u2624099/data/www/aaa.store/wp-content/plugins/wordpress-seo/src/presentations/abstract-presentation.php(66): Yoast\WP\SEO\Presentations\Indexable_Post_Type_Presentation->generate_open_graph_description()
#25 /var/www/u2624099/data/www/aaa.store/wp-content/plugins/wordpress-seo/src/presenters/open-graph/description-presenter.php(33): Yoast\WP\SEO\Presentations\Abstract_Presentation->__get('open_graph_desc...')
#26 /var/www/u2624099/data/www/aaa.store/wp-content/plugins/wordpress-seo/src/presenters/abstract-indexable-tag-presenter.php(37): Yoast\WP\SEO\Presenters\Open_Graph\Description_Presenter->get()
#27 /var/www/u2624099/data/www/aaa.store/wp-content/plugins/wordpress-seo/src/integrations/front-end-integration.php(406): Yoast\WP\SEO\Presenters\Abstract_Indexable_Tag_Presenter->present()
#28 /var/www/u2624099/data/www/aaa.store/wp-includes/class-wp-hook.php(324): Yoast\WP\SEO\Integrations\Front_End_Integration->present_head('')
#29 /var/www/u2624099/data/www/aaa.store/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#30 /var/www/u2624099/data/www/aaa.store/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#31 /var/www/u2624099/data/www/aaa.store/wp-content/plugins/wordpress-seo/src/integrations/front-end-integration.php(377): do_action('wpseo_head')
#32 /var/www/u2624099/data/www/aaa.store/wp-includes/class-wp-hook.php(324): Yoast\WP\SEO\Integrations\Front_End_Integration->call_wpseo_head('')
#33 /var/www/u2624099/data/www/aaa.store/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#34 /var/www/u2624099/data/www/aaa.store/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#35 /var/www/u2624099/data/www/aaa.store/wp-includes/general-template.php(3065): do_action('wp_head')
#36 /var/www/u2624099/data/www/aaa.store/wp-content/themes/aaa/header.php(24): wp_head()
#37 /var/www/u2624099/data/www/aaa.store/wp-includes/template.php(810): require_once('/var/www/u26240...')
#38 /var/www/u2624099/data/www/aaa.store/wp-includes/template.php(745): load_template('/var/www/u26240...', true, Array)
#39 /var/www/u2624099/data/www/aaa.store/wp-includes/general-template.php(48): locate_template(Array, true, true, Array)
#40 /var/www/u2624099/data/www/aaa.store/wp-content/themes/aaa/page.php(16): get_header()
#41 /var/www/u2624099/data/www/aaa.store/wp-includes/template-loader.php(106): include('/var/www/u26240...')
#42 /var/www/u2624099/data/www/aaa.store/wp-blog-header.php(19): require_once('/var/www/u26240...')
#43 /var/www/u2624099/data/www/aaa.store/index.php(17): require('/var/www/u26240...')
#44 {main}
  thrown in /var/www/u2624099/data/www/aaa.store/wp-content/plugins/cdekdelivery/src/CdekApi.php on line 296`

**Comment by vermorag** [comment]
Добрый день, можете подсказать версию установленного плагина?

**Comment by denism300** [comment]
![image](https://github.com/user-attachments/assets/67979236-bd98-464b-acab-c3a0280ce694)
3.23.3

**Comment by vermorag** [comment]
Установите, пожалуйста, актуальную [3.22.3](https://github.com/cdek-it/wordpress/releases/tag/v3.22.3) версию и проверьте ошибку на ней.

**Comment by denism300** [comment]
С версией [https://github.com/cdek-it/wordpress/releases/tag/v3.22.4](v3.22.4) все ок
